module.exports = {
	extends: ['@ptsecurity/commitlint-config'],
	rules: {
		'scope-enum': [
			2,
			'always',
			[
				'accounts',
				'activity',
				'assets',
				'backup',
				'contacts',
				'lang',
				'lightning',
				'onboarding',
				'profile',
				'receive',
				'scan',
				'security',
				'send',
				'settings',
				'suggestions',
				'tokens',
				'ui',
				'wallet',
				'widgets',
			],
		],
	},
	ignores: [(msg) => /\bWIP\b/i.test(msg)],
};
