name: tests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  tests:
    name: Run jest unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run regtest setup
        run: cd __tests__ && docker compose up -d

      - name: Wait for bitcoind and chmod 777 cookie file
        # because bitcoind and electrs has different user ids and bitcoind creates cookie file with chmod 700
        # electrum server can't read it, that is why we chmod 777 it
        run: |
          sudo apt install wait-for-it
          wait-for-it -h 127.0.0.1 -p 43782 -t 60
          sudo chmod 777 __tests__/bitcoin_datadir/regtest/.cookie

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TEST_USER_SSH_KEY }}
          known_hosts: ${{ secrets.TEST_USER_KNOWN_HOSTS }}

      - name: Use NPM Token with organization read access
        uses: dkershner6/use-npm-token-action@v1
        with:
          token: '${{ secrets.NPMJS_READ }}'

      - name: Install Node.js dependencies
        run: yarn install

      - name: Wait for electrum server
        run: wait-for-it -h 127.0.0.1 -p 60001 -t 60

      - name: Run Tests
        run: yarn test

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
