name: tests

on: pull_request

jobs:
  tests:
    name: Run jest unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run regtest setup
        run: cd docker && docker compose up --quiet-pull -d

      - name: Wait for bitcoind
        run: |
          sudo apt install wait-for-it
          wait-for-it -h 127.0.0.1 -p 43782 -t 60

      - name: Wait for electrum server
        run: wait-for-it -h 127.0.0.1 -p 60001 -t 60

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17
          cache: 'yarn'

      - name: Install Node.js dependencies
        run: yarn install || yarn install

      - name: Activate enviroment variables
        run: cp .env.development.template .env

      - name: Run Tests
        run: yarn test

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
